FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    ca-certificates \
    cmake \
    git \
    python3 \
    python3-pip \
    curl \
    gdb \
    lldb \
    valgrind \
    clang-18 \
    clang-format-18 \
    clang-tidy-18 \
    gcc-13 \
    g++-13 \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --no-cache-dir pre-commit cmake-format codespell

WORKDIR /work
